# setup
setup: reliability

# Model
backbone: resnet18
num_heads: 1
update_cluster_head_only: False
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
train_db_name: cifar-10
val_db_name: cifar-10
num_classes: 10

# Transformations
transformation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]

# Hyperparameters
batch_size: 1000
num_workers: 8